"""change data type of audit log branch id

Revision ID: 2800f6d2932e
Revises: f2bc63d56c1b
Create Date: 2026-03-17 12:44:22.165054

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '2800f6d2932e'
down_revision = 'f2bc63d56c1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First drop the constraint that depends on the column
    op.drop_constraint('audit_logs_branch_id_fkey', 'audit_logs', type_='foreignkey')
    # Now alter the column type
    op.alter_column('audit_logs', 'branch_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True,
               postgresql_using='branch_id::text')
    # Finally create the new foreign key constraint
    op.create_foreign_key('audit_logs_branch_id_fkey', 'audit_logs', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First drop the new constraint
    op.drop_constraint('audit_logs_branch_id_fkey', 'audit_logs', type_='foreignkey')
    
    # Alter the column back to UUID
    op.alter_column('audit_logs', 'branch_id',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='branch_id::uuid')
               
    # Restore the old foreign key constraint
    op.create_foreign_key('audit_logs_branch_id_fkey', 'audit_logs', 'branches', ['branch_id'], ['uid'])
    # ### end Alembic commands ###

