"""create user table

Revision ID: 37e75977674e
Revises: dd97d9a4f776
Create Date: 2026-03-07 16:20:58.573406

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '37e75977674e'
down_revision = 'dd97d9a4f776'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.add_column('roles', sa.Column('uuid', sa.UUID(), nullable=False))
    op.alter_column('roles', 'name',
               existing_type=postgresql.ENUM('admin', 'branch_manager', 'staff', 'customer', name='role_type'),
               type_=sa.Enum('admin', 'branch_manager', 'staff', 'customer', name='role_type'),
               existing_nullable=False)
    op.create_index(op.f('ix_roles_uuid'), 'roles', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_uuid'), table_name='roles')
    op.alter_column('roles', 'name',
               existing_type=sa.Enum('admin', 'branch_manager', 'staff', 'customer', name='role_type'),
               type_=postgresql.ENUM('admin', 'branch_manager', 'staff', 'customer', name='role_type'),
               existing_nullable=False)
    op.drop_column('roles', 'uuid')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

