"""create customer-profile table

Revision ID: 60496adfcb96
Revises: 37e75977674e
Create Date: 2026-03-07 16:22:11.487323

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '60496adfcb96'
down_revision = '37e75977674e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=postgresql.ENUM('admin', 'branch_manager', 'staff', 'customer', name='role_type'),
               type_=sa.Enum('admin', 'branch_manager', 'staff', 'customer', name='role_type'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=sa.Enum('admin', 'branch_manager', 'staff', 'customer', name='role_type'),
               type_=postgresql.ENUM('admin', 'branch_manager', 'staff', 'customer', name='role_type'),
               existing_nullable=False)
    # ### end Alembic commands ###

