"""change customer profile table and staff profile table

Revision ID: 72789556d6e7
Revises: 80dd16c64430
Create Date: 2026-03-15 20:59:04.688485

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '72789556d6e7'
down_revision = '80dd16c64430'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_profiles', 'id_image_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_constraint('staff_profiles_role_fkey', 'staff_profiles', type_='foreignkey')
    op.alter_column('staff_profiles', 'role',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('staff_profiles_role_fkey', 'staff_profiles', 'roles', ['role'], ['id'])
    op.alter_column('staff_profiles', 'role',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('customer_profiles', 'id_image_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###

