"""Add phone to branch

Revision ID: 80dd16c64430
Revises: 8de692477bd4
Create Date: 2026-03-11 23:41:46.499299

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '80dd16c64430'
down_revision = '8de692477bd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'audit_logs', ['uid'])
    op.add_column('branches', sa.Column('phone', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'phone')
    op.drop_constraint(None, 'audit_logs', type_='unique')
    # ### end Alembic commands ###

