"""fix role enum issue

Revision ID: 857d1aef22d3
Revises: 60496adfcb96
Create Date: 2026-03-07 16:45:14.795835

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '857d1aef22d3'
down_revision = '60496adfcb96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

