"""alter capacity of slot

Revision ID: 8c58909cb773
Revises: 2800f6d2932e
Create Date: 2026-03-17 12:51:53.705297

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8c58909cb773'
down_revision = '2800f6d2932e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slots', 'capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slots', sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###

