"""create all requried tables

Revision ID: 8de692477bd4
Revises: 6c694e8fda40
Create Date: 2026-03-09 00:20:36.389401

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '8de692477bd4'
down_revision = '6c694e8fda40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('branches',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_branches_uid'), 'branches', ['uid'], unique=False)
    op.create_table('service_types',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('branch_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text, nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_service_types_uid'), 'service_types', ['uid'], unique=False)
    op.create_table('staff_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_staff_profiles_id'), 'staff_profiles', ['id'], unique=False)
    op.create_table('slots',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('branch_id', sa.String(length=100), nullable=False),
    sa.Column('service_type_id', sa.String(length=100), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_profiles.id'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_slots_uid'), 'slots', ['uid'], unique=False)
    op.create_table('staff_service_types',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_profiles.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_staff_service_types_uid'), 'staff_service_types', ['uid'], unique=False)
    op.create_table('appoinments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appoinment_no', sa.String(length=100), nullable=False),
    sa.Column('branch_id', sa.String(length=100), nullable=False),
    sa.Column('slot_id', sa.String(length=100), nullable=True),
    sa.Column('service_type_id', sa.String(length=100), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appoinment_no')
    )
    op.create_index(op.f('ix_appoinments_id'), 'appoinments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appoinments_id'), table_name='appoinments')
    op.drop_table('appoinments')
    op.drop_index(op.f('ix_staff_service_types_uid'), table_name='staff_service_types')
    op.drop_table('staff_service_types')
    op.drop_index(op.f('ix_slots_uid'), table_name='slots')
    op.drop_table('slots')
    op.drop_index(op.f('ix_staff_profiles_id'), table_name='staff_profiles')
    op.drop_table('staff_profiles')
    op.drop_index(op.f('ix_service_types_uid'), table_name='service_types')
    op.drop_table('service_types')
    op.drop_index(op.f('ix_branches_uid'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###

