"""update appointment table

Revision ID: e9f8d530a755
Revises: 72789556d6e7
Create Date: 2026-03-15 23:11:18.282666

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'e9f8d530a755'
down_revision = '72789556d6e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create the enum type
    appointment_status = sa.Enum('BOOKED', 'CHECKED_IN', 'NO_SHOW', 'COMPLETED', 'CANCELLED', name='appointment_status')
    appointment_status.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appoinments', sa.Column('customer_id', sa.UUID(), nullable=False))
    op.add_column('appoinments', sa.Column('attachment_path', sa.String(length=500), nullable=True))
    op.alter_column('appoinments', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('BOOKED', 'CHECKED_IN', 'NO_SHOW', 'COMPLETED', 'CANCELLED', name='appointment_status'),
               existing_nullable=False,
               postgresql_using='status::appointment_status')
    op.create_foreign_key(None, 'appoinments', 'users', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appoinments', type_='foreignkey')
    op.alter_column('appoinments', 'status',
               existing_type=sa.Enum('BOOKED', 'CHECKED_IN', 'NO_SHOW', 'COMPLETED', 'CANCELLED', name='appointment_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('appoinments', 'attachment_path')
    op.drop_column('appoinments', 'customer_id')
    # ### end Alembic commands ###
    
    # Drop the enum type
    appointment_status = sa.Enum('BOOKED', 'CHECKED_IN', 'NO_SHOW', 'COMPLETED', 'CANCELLED', name='appointment_status')
    appointment_status.drop(op.get_bind())

