"""add branch_id in auditlogs

Revision ID: f2bc63d56c1b
Revises: e9f8d530a755
Create Date: 2026-03-17 12:35:26.340553

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'f2bc63d56c1b'
down_revision = 'e9f8d530a755'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'audit_logs', 'branches', ['branch_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'branch_id')
    # ### end Alembic commands ###

